package view;

import controller.Controller;
import java.awt.Color;
import model.Player;

/**
 *
 * @author rober
 */
public final class Preferences extends javax.swing.JPanel {

    public Preferences() {
        initComponents();
        jrbg_modes.add(jrb_manual);
        jrbg_modes.add(jrb_automatic);
        jrbg_colors.add(jrb_yellow);
        jrbg_colors.add(jrb_red);
        visible(false);
        
    }
    
    public void addListeners(Controller controller) {
        jb_start.addActionListener(controller);
        jtf_player1.addFocusListener(controller);
        jrb_red.addActionListener(controller);
        jrb_yellow.addActionListener(controller);
        jrb_manual.addActionListener(controller);
        jrb_automatic.addActionListener(controller);
        jtf_player2.addFocusListener(controller);
    }
    
    public void focusOff(Object focus) {
        if(focus == jtf_player1) {
            if (jtf_player1.getText().isEmpty() || jtf_player1.getText().trim().length() == 0) {
                jtf_player1.setText("Insert name");
                jtf_player1.setForeground(Color.gray);
            }
        }
        else {
            if (jtf_player2.getText().isEmpty() || jtf_player2.getText().trim().length() == 0) {
                jtf_player2.setText("Insert name");
                jtf_player2.setForeground(Color.gray);
            }
        }
    }
    
    public void focusOn(Object focus) {
        if(focus == jtf_player1) {
            if (jtf_player1.getText().equals("Insert name")) {
                jtf_player1.setText("");
                jtf_player1.setForeground(Color.black);
            }
        }
        else {
            if (jtf_player2.getText().equals("Insert name")) {
                jtf_player2.setText("");
                jtf_player2.setForeground(Color.black);
            }
        }
    }
    
    public Player getPlayer() {
        return new Player(getPlayer1(), jrbg_colors.getSelection().getActionCommand(),
                jrbg_modes.getSelection().getActionCommand(), getPlayer2());
    }
    
    public void setPlayers() {
        jtf_player1.setText(getPlayer1());
        jtf_player2.setText(getPlayer2());
    }
    
    public String getPlayer1() {
        return (jtf_player1.getText().equals("Insert name")) ? "Player #1" : jtf_player1.getText();
    }
    
    public String getPlayer2() {
        return (jtf_player2.getText().equals("Insert name")) ? "Player #2" : jtf_player2.getText();
    }
    
    public void visible(boolean mode) {
        if(mode) {
            jl_player2.setVisible(true);
            jtf_player2.setVisible(true);
        }
        else {
            jl_player2.setVisible(false);
            jtf_player2.setVisible(false);
        }
    }
    
    public void disableAll() {
        jtf_player1.setEnabled(false);
        jrb_red.setEnabled(false);
        jrb_yellow.setEnabled(false);
        jrb_manual.setEnabled(false);
        jrb_automatic.setEnabled(false);
        jtf_player2.setEnabled(false);
        jb_start.setEnabled(false);
    }
    
    public void enableOptions() {
        jtf_player1.setEnabled(true);
        jrb_red.setEnabled(true);
        jrb_yellow.setEnabled(true);
        jrb_manual.setEnabled(true);
        jrb_automatic.setEnabled(true);
        jtf_player2.setEnabled(true);
        jb_start.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrbg_modes = new javax.swing.ButtonGroup();
        jrbg_colors = new javax.swing.ButtonGroup();
        jl_player = new javax.swing.JLabel();
        jtf_player1 = new javax.swing.JTextField();
        jl_mode = new javax.swing.JLabel();
        jrb_manual = new javax.swing.JRadioButton();
        jrb_automatic = new javax.swing.JRadioButton();
        jl_color = new javax.swing.JLabel();
        jrb_red = new javax.swing.JRadioButton();
        jrb_yellow = new javax.swing.JRadioButton();
        jb_start = new javax.swing.JButton();
        jl_player2 = new javax.swing.JLabel();
        jtf_player2 = new javax.swing.JTextField();

        jl_player.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jl_player.setText("Player:");

        jtf_player1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        jtf_player1.setForeground(new java.awt.Color(153, 153, 153));
        jtf_player1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_player1.setText("Insert name");
        jtf_player1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtf_player1.setPreferredSize(new java.awt.Dimension(2, 24));

        jl_mode.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jl_mode.setText("Mode:");

        jrb_manual.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        jrb_manual.setText("Manual");
        jrb_manual.setNextFocusableComponent(jrb_automatic);
        jrb_manual.setVerifyInputWhenFocusTarget(false);

        jrb_automatic.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        jrb_automatic.setSelected(true);
        jrb_automatic.setText("Automatic");

        jl_color.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jl_color.setText("Color:");

        jrb_red.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        jrb_red.setSelected(true);
        jrb_red.setText("Red");

        jrb_yellow.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        jrb_yellow.setText("Yellow");

        jb_start.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jb_start.setText("START");

        jl_player2.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        jl_player2.setText("Player:");

        jtf_player2.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        jtf_player2.setForeground(new java.awt.Color(153, 153, 153));
        jtf_player2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtf_player2.setText("Insert name");
        jtf_player2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtf_player2.setPreferredSize(new java.awt.Dimension(2, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_mode)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jl_player, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_color)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_start)
                            .addComponent(jtf_player1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb_manual)
                                    .addComponent(jrb_red))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrb_yellow)
                                    .addComponent(jrb_automatic)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_player2)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_player2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_player)
                    .addComponent(jtf_player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_color)
                    .addComponent(jrb_red)
                    .addComponent(jrb_yellow))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_mode)
                    .addComponent(jrb_manual)
                    .addComponent(jrb_automatic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_player2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_player2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_start)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_start;
    private javax.swing.JLabel jl_color;
    private javax.swing.JLabel jl_mode;
    private javax.swing.JLabel jl_player;
    private javax.swing.JLabel jl_player2;
    private javax.swing.JRadioButton jrb_automatic;
    private javax.swing.JRadioButton jrb_manual;
    private javax.swing.JRadioButton jrb_red;
    private javax.swing.JRadioButton jrb_yellow;
    private javax.swing.ButtonGroup jrbg_colors;
    private javax.swing.ButtonGroup jrbg_modes;
    private javax.swing.JTextField jtf_player1;
    private javax.swing.JTextField jtf_player2;
    // End of variables declaration//GEN-END:variables

}
